// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGn17_wrc2CJWSMvl475ihT2F07wPsO8M',
    appId: '1:570573776201:web:a52e6c0b765026aed22698',
    messagingSenderId: '570573776201',
    projectId: 'hcms-a41be',
    authDomain: 'hcms-a41be.firebaseapp.com',
    storageBucket: 'hcms-a41be.firebasestorage.app',
    measurementId: 'G-L0QYZ4G8QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZcQFQn8Uq1kuAGoEuQKjTVvuJmb28e0c',
    appId: '1:570573776201:android:dfd83ce8bf7875ced22698',
    messagingSenderId: '570573776201',
    projectId: 'hcms-a41be',
    storageBucket: 'hcms-a41be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoeT6GwXdMzBUQlkdTj0U77gt9b2qLQbQ',
    appId: '1:570573776201:ios:aec201fd26d6e730d22698',
    messagingSenderId: '570573776201',
    projectId: 'hcms-a41be',
    storageBucket: 'hcms-a41be.firebasestorage.app',
    iosBundleId: 'com.example.hcms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoeT6GwXdMzBUQlkdTj0U77gt9b2qLQbQ',
    appId: '1:570573776201:ios:aec201fd26d6e730d22698',
    messagingSenderId: '570573776201',
    projectId: 'hcms-a41be',
    storageBucket: 'hcms-a41be.firebasestorage.app',
    iosBundleId: 'com.example.hcms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGn17_wrc2CJWSMvl475ihT2F07wPsO8M',
    appId: '1:570573776201:web:4532d101a40fcc89d22698',
    messagingSenderId: '570573776201',
    projectId: 'hcms-a41be',
    authDomain: 'hcms-a41be.firebaseapp.com',
    storageBucket: 'hcms-a41be.firebasestorage.app',
    measurementId: 'G-92Y4114GB2',
  );
}
